export const SEARCH_INPROGRESS = 'SEARCH_INPROGRESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const REPO_FETCH_INPROGRESS = "REPO_FETCH_INPROGRESS";
export const REPO_FETCH_ERROR = "REPO_FETCH_ERROR";
export const REPO_FETCH_SUCCESS = "REPO_FETCH_SUCCESS";